# Production Configuration
spring.application.name=equitrust

# Server - RENDER USA PUERTO 10000
#server.port=${PORT:10000}
server.port=${PORT:8080}

# Database Configuration (usando variables de entorno)
#spring.datasource.url=${DATABASE_URL}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# WebSocket Configuration
websocket.allowed.origins=${WEBSOCKET_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000}

# MongoDB Configuration (para Chat y otros documentos)
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/equitrust}
spring.data.mongodb.auto-index-creation=true

# JPA/Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=false
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
logging.level.org.hibernate=DEBUG

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# CORS Configuration
app.cors.origins=${CORS_ORIGINS}

# Logging
logging.level.org.springframework.security=INFO
logging.level.com.nocountry.equitrust=INFO

# Error handling
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never
server.error.include-exception=false

# Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method