spring.application.name=equitrust
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/equitrust_db
spring.datasource.username=postgres
spring.datasource.password=admin
# Database Configuration
spring.datasource.driver-class-name=org.postgresql.Driver


# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D635166546A576E5A7234753778214125442A
jwt.expiration=86400000



# Server
server.port=8080

# CORS Configuration
# Para desarrollo local, separar múltiples orígenes con coma
app.cors.origins=http://localhost:5173,http://localhost:3000
# Para producción, cambiar a:
# app.cors.origins=https://dom.com,https://www.dom.com

# JPA/Hibernate - IMPORTANTE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.nocountry.equitrust=DEBUG

# Error handling
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param
server.error.include-exception=false

# Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Cloudinary
cloudinary.url=${CLOUDINARY_URL}
cloudinary.horse.photos=${CLOUDINARY_HORSE_PHOTOS:horsetrust/horses/photos}
cloudinary.horse.videos=${CLOUDINARY_HORSE_VIDEOS:horsetrust/horses/videos}

# File Upload Limits
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB